### ISSUE TITLE
NullPointerException at mobile token /authenticate method

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#101]
After the operation expires, NPE is thrown:

```
java.lang.NullPointerException: null
	at io.getlime.security.powerauth.lib.webflow.authentication.mtoken.controller.MobileTokenController.checkOperationStatus(MobileTokenController.java:135) ~[powerauth-webflow-authentication-mtoken-0.15.0.jar:0.15.0]
	at sun.reflect.GeneratedMethodAccessor803.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.9.RELEASE.jar:4.3.9.RELEASE]
```

**Comment by romanstrobl** [comment]
Call of getOperation() returns null for expired operations, I will look into this.
