### ISSUE TITLE
Clicking twice on Cancel leads to a 500 error

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-webflow#102]
When you click twice on Cancel (you have to do it really quickly), the regular flow is interrupted with a 500 error.

**Comment by petrdvorak** [comment]
Stack trace:

```
java.lang.IllegalStateException: Operation update failed, because operation is already in FAILED state (operationId: d375ee91-bc9e-4aa9-943d-bda990640079).
	at io.getlime.security.powerauth.app.nextstep.service.StepResolutionService.checkLegitimityOfUpdate(StepResolutionService.java:362) ~[classes/:0.15.0]
	at io.getlime.security.powerauth.app.nextstep.service.StepResolutionService.resolveNextStepResponse(StepResolutionService.java:121) ~[classes/:0.15.0]
	at io.getlime.security.powerauth.app.nextstep.controller.OperationController.updateOperation(OperationController.java:89) ~[classes/:0.15.0]
	at sun.reflect.GeneratedMethodAccessor810.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
...
```
